# https://taskfile.dev
version: '3'

silent: true

vars:
  GO_MODULE: github.com/evgeniy-krivenko/chat-service
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./internal/store/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.52.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/Library/Caches/golangci-lint"

  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.8.0
    mvdan.cc/gofumpt@v0.4.0
    github.com/kazhuravlev/options-gen/cmd/options-gen@v0.28.4
    entgo.io/ent/cmd/ent@v0.11.10

  WORKDIR:
    sh: echo "$(pwd)"

  DEV_TOOLS_PATH: /tools/bin

  DOCKER_COMPOSE_PATHS: |
    ./deploy/local/docker-compose.yml
    ./deploy/local/docker-compose.sentry.yml

  # if it will be decided generate key with every deps running
  SENTRY_SECRET_KEY_DEPS: |
    {{if eq $.COMPOSE_PROFILES "sentry"}} `docker run --platform linux/amd64 --rm sentry config generate-secret-key` {{end}}

  DOCKER_FILES: |
    {{range $file := .DOCKER_COMPOSE_PATHS | trim | splitLines -}}
      \-f {{$file}} \
    {{end -}}

  DOCKER_COMPOSE_CMD: docker compose

  TYPES: |
    ChatID
    MessageID
    ProblemID
    UserID
  TYPES_PKG: types
  TYPES_DST: ./internal/types/types.gen.go

  SCHEMA_PATH: ./internal/store/schema

tasks:
  default:
    # Последовательно выполняем таски tidy, fmt, lint, tests и build
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  gen:types:
    cmds:
      - echo "Generate types..."
      - |
        go run ./cmd/gen-types {{.TYPES_PKG}} \
        {{range $index, $type := .TYPES | trim | splitLines -}}
        {{if $index}},{{- end -}}
        {{$type -}}
        {{end}} \
        {{.TYPES_DST}}

  ent:gen:
    cmds:
      - .{{.DEV_TOOLS_PATH}}/ent generate {{.SCHEMA_PATH}}
      - task: tidy

  ent:new:
    cmds:
      - .{{.DEV_TOOLS_PATH}}/ent new --target {{.SCHEMA_PATH}} {{.CLI_ARGS}}
      - task: tidy


  generate:
    cmds:
      - echo "Run go generate..."
      - export PATH=$PATH:{{.WORKDIR}}{{.DEV_TOOLS_PATH}} && go generate ./...
      - task: gen:types
      - task: ent:gen

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - .{{.DEV_TOOLS_PATH}}/gofumpt -w  {{.GO_FILES}}
    - .{{.DEV_TOOLS_PATH}}/gci write -s standard -s default -s "prefix({{.GO_MODULE}})" {{.GO_FILES}}

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: {CLI_ARGS: "run -v --fix --timeout=5m ./..."}

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -v -race ./... {{.CLI_ARGS}}

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service

  dev-tools:install:
    cmds:
      - echo "- Install dev tools"
      - mkdir -p .{{.DEV_TOOLS_PATH}}
      - |
        {{range $tool := .DEV_TOOLS | trim | splitLines -}}
          GOBIN={{$.WORKDIR}}{{$.DEV_TOOLS_PATH}} go install {{$tool}}
        {{end -}}
        
  deps:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} up -d"

  deps:cmd:
    env:
      # for seeing containers status without throwing env
      COMPOSE_PROFILES: sentry
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} {{.CLI_ARGS}}"

  deps:status:
    env:
      # for seeing containers status without throwing env
      COMPOSE_PROFILES: sentry
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} ps"

  deps:logs:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} logs {{.CLI_ARGS}}"

  deps:stop:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} stop"

  deps:reset-psql:
    cmds:
      - task: deps:reset
        vars:
          SERVICE: postgres

  deps:reset:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} rm -fsv {{.SERVICE}}"
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_FILES}} up -d {{.SERVICE}}"
