// Code generated by ent, DO NOT EDIT.

package failedjob

import (
	"time"

	"github.com/evgeniy-krivenko/chat-service/internal/types"
)

const (
	// Label holds the string label denoting the failedjob type in the database.
	Label = "failed_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the failedjob in the database.
	Table = "failed_jobs"
)

// Columns holds all SQL columns for failedjob fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPayload,
	FieldReason,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() types.FailedJobID
)
