version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    profiles: [ "swagger-ui" ]
    platform: linux/amd64
    ports:
      - "127.0.0.1:3011:8080"
    environment:
      URLS: "[{ url: 'doc/client.v1.swagger.yml', name: 'ClientV1' }]"
    volumes:
      - ../../api:/usr/share/nginx/html/doc
