version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: chat-service
      POSTGRES_USER: chat-service
      POSTGRES_PASSWORD: chat-service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    depends_on:
      - postgres
    command:
      - start-dev --import-realm
    volumes:
      - .:/tmp/keycloak-export
      - ./bank-realm.json:/opt/keycloak/data/import/bank-realm.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:3010:8080"

  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "chat.messages:16:1,afc.msg-verdicts:16:1,afc.msg-verdicts.dlq:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  afc_emulator:
    image: antonboom/writing-go-service.afc
    depends_on:
      - kafka
    restart: on-failure
    environment:
      AFC_LOG_LEVEL: "DEBUG"
      AFC_BROKER_ADDR: "kafka:29092"
      AFC_MESSAGES_TOPIC: "chat.messages"
      AFC_VERDICTS_TOPIC: "afc.msg-verdicts"
      AFC_VERDICTS_SIGN_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXQIBAAKBgQCzsJUib292dGpphy+6Pq6EiqfMmPMkfpe+ZtO6UQOuccCshNPx
        JSMVoPUwLexDRG1axcgpuvJWnCvcV93RQIE2tsUrDzEnO627eSs0TOEn4hJzLsI2
        S6LcJP7QItbTAOBMgVR0Br6eVBLK1fOwxKrGE3nlySk6FlhhzeP2gFhQZQIDAQAB
        AoGAey5fXibkU2EFHeilyFh2DLh8xZ5IeEksP0OAe+ZTzr9+ZQX9wP9DaO1ZiDjD
        EW4URTj2udzFiqguzTOTBYLh0Hf63VZXimDfACG6UFaUL65Bha2sEVx1c/Eh1oDG
        u0nSxsaSk7HDY3SZ6faDZwqYr2eAmxOXt7xtTJOMOta9ndUCQQDq/S1zmfXdlt9d
        jZN6DSrLm6wRhLY99fxVhv1MYD8M9BnL1VZGJ4O4VQSbNYbPtyFVxfvYlYwkPLAG
        gs2ednpHAkEAw8GfwK4xLVnbwZJBHkqJazj4dAeqAASWyo1Eil0BHU7NBKLKa76d
        ETHe3aIdUYIQCSnA7Ggx9ZEWXPZaCNxJ8wJBAInNLno8LxJjB1m1TGamkhIUmDMt
        wDFVr0P4hVHknxTZkMcXtCAvy+6s7KaYHRZyLfo+wBGioSwe6prm2e2zTMECQH6j
        WxLOXbgGArmGQSQ0ehPoZirB7oNWdKqSmz2bjyYDnXQbUDJFvNyr046z2p2pM3CK
        F2mYuoEvnDUFlhdXU2sCQQC/dV9JzO10H4TwyK5Fhhl0unTssbmD/+xjWaKcxxo/
        a/eFeHFanU6MfLaB0hi/g0frCLVYoXqGLgaJIEfDDfNF
        -----END RSA PRIVATE KEY-----

volumes:
  postgresql-data:
