version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    profiles: [ "swagger-ui" ]
    platform: linux/amd64
    ports:
      - "127.0.0.1:3011:8080"
    environment:
      URLS: "[{ url: 'doc/client.v1.swagger.yml', name: 'Bank Client V1' },
      { url: 'doc/manager.v1.swagger.yml', name: 'Bank Manager V1' }, 
      { url: 'doc/client.events.swagger.yml', name: 'Bank Client Events' }]
      { url: 'doc/manager.events.swagger.yml', name: 'Bank Manager Events' }]
      "
    volumes:
      - ../../api:/usr/share/nginx/html/doc
