version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: chat-service
      POSTGRES_USER: chat-service
      POSTGRES_PASSWORD: chat-service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    depends_on:
      - postgres
    command:
      - start-dev --import-realm
    volumes:
      - .:/tmp/keycloak-export
      - ./bank-realm.json:/opt/keycloak/data/import/bank-realm.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:3010:8080"

  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "chat.messages:16:1,afc.msg-verdicts:16:1,afc.msg-verdicts.dlq:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  afc_emulator:
    image: antonboom/writing-go-service.afc
    depends_on:
      - kafka
    restart: on-failure
    environment:
      AFC_LOG_LEVEL: "DEBUG"
      AFC_BROKER_ADDR: "kafka:29092"
      AFC_MESSAGES_TOPIC: "chat.messages"
      AFC_VERDICTS_TOPIC: "afc.msg-verdicts"
      AFC_VERDICTS_SIGN_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEAtgvlzbMKiU4hmWAdOtmLNyeO+6L9es6m+2Z/m5CaCijywMES
        p8gQaOkCIxUpfmNa4zTC7BTNtBB0Nk9NoXt60ZS5EPcvbgVRSqV410bZ4TrKrFdU
        Qe3CD880xs8VDgPJdq7fxu+tuOzwbFGCvlLJe6naaUeV0aqGiiBf56E7bGzKfYYS
        ND3sNL7byhZef0N845f2lUK7QKQsS4KYxhi7V0/FyOWvdaY3Yz/MJ+82hzC+A41r
        Y1Y3/rIx1wMszA68F1ug5lDI0s4REFVt9z3yDyntB2GGofqQZMVuMFecivKF36zR
        kZ1Rzvce9YKB1C/2Wdy8DomWDDL/p9+XEXmjVwIDAQABAoIBAFbf6KO4PF/37CrQ
        ZkKOTFReyWomhwaTFbbFXEI1yHzuu6HmwWtWGxalk4KAd9O7wETLCfY1m1DBxWOh
        hq94SM05RvPksjqzyO5xdvBs/E7yioOiDTCFMOXwgQQbELYmcn7zxxCdkm68i6N1
        ZopC4anlDbjOE54B3cCO4JWeKMh9d586bL+y9GgYvaFbwdopSJ7oDE5+UlbNavC+
        OPic57N939dNaeyPxeL2M0IQ8UhfPD4wuSfPvhmkyV92V5WKP5oqZ7INlsPbJvYO
        O6HIZnoy6Soee+kYGFPJ1v/+ulpzdGJ780TV3RWLDGv/V7uzsrkUxUmJ/5XMyMbP
        6v18poECgYEA6UAoJBB02PwSNiNUymOnBe5LoYHQpXV3BxiTmJ4nX3pMN8W0K3JH
        yatzQLaekY5SvGdjnTHQXYZfbbJdI0qFkRVtI0P1gdx4sToq9l84cwr3aeF8ujVh
        6KhJYd04xTeHoQFDfcfiFk8V/GN/AmtCazwrRj5EsviAH7xG01RFepcCgYEAx81E
        SyiCySabn6Jfr9+ioU7kAcrxJB3/rV7t1zKHEXRPHr8F3F37+n5YOC2UKdHHBlJD
        7CGm8JFMTK7Bf7q8s9LwWZkc46DN7En/Isz03o9tvT+EX6jM3eRlPK1w46S7wFI9
        s2ufRYX8FPMLwk8oFRE001Rt1nsvMuQu51319UECgYAVWrpSEu+frfQ84J8yqEzy
        Tg6+ipP/kfGDxMw+fLw+EYRI1uDX2W6ZGAlFM3LxAIaymQSVr6nT5il2cY31XS09
        SyjiwaYIbZbfIuQsCiuw3KAqIWq54YlFM6MEQqyf4aWZJ/R134bjY/ovUSyfnBJI
        nwmXNLw1ZmrUfPg/AMgboQKBgAJ7TDPaxvUUo64x6BpZHr3+KtrS2HfoX3qZyT55
        BDB1T15EZSA9kpmj5BieiE6UqnIrp2hRaq9mPppdOU4K1bkuD4otWqyBHM2ohaC7
        BveUtHo7Rbuibxj6cz9zsAlDzIkw/E80MQA+D8l601SQgyDv28YcMFkPoqBxMRvy
        kNGBAoGAW2Ii1MR3cWuHPEh8oO5Y6SGPU8ReFw3ndUd2F9OOlkV4/FQ+mu2d8EZd
        e0x/zY2Yom0EcBIqembgpdF6IPStIRpdLES4DETnhssX2MEpbGEwR6nlK2ZD5lxG
        5+8ylPL8QstiM3s22cxb/6dL/M/DX0Z8Ay4Ft0abX9Jphf3EbdA=
        -----END RSA PRIVATE KEY-----

volumes:
  postgresql-data:
