// Code generated by options-gen. DO NOT EDIT.
package serverdebug

import (
	fmt461e464ebed9 "fmt"

	"github.com/getkin/kin-openapi/openapi3"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	addr string,
	v1Client *openapi3.T,
	v1Manager *openapi3.T,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.addr = addr
	o.v1Client = v1Client
	o.v1Manager = v1Manager

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("addr", _validate_Options_addr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("v1Client", _validate_Options_v1Client(o)))
	errs.Add(errors461e464ebed9.NewValidationError("v1Manager", _validate_Options_v1Manager(o)))
	return errs.AsError()
}

func _validate_Options_addr(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.addr, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `addr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_v1Client(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.v1Client, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `v1Client` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_v1Manager(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.v1Manager, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `v1Manager` did not pass the test: %w", err)
	}
	return nil
}
