[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "some-protocol-for-auth"
[servers.client.required_access]
resource = "some-resource"
role = "some-role"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "some-protocol-for-auth"
[servers.manager.required_access]
resource = "some-resourse"
role = "some-role"

[sentry]
dsn = "https://example.com"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "realm"
client_id = "client_id"
client_secret = "secret"
debug_mode = false

[db]
addr = "127.0.0.1:5432"
user = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = true

[services]
[services.msg_producer]
brokers = ["localhost:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "68566D597133743677397A2443264629" # Leave it blank to disable encryption. hexdemical string

[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"

[services.manager_load]
max_problems_at_same_time = 5

[services.afc_verdicts_processor]
brokers = ["localhost:9092"]
consumers = 2
consumer_group = "some group id"
verdicts_topic = "topic for verdicts msg"
verdicts_dlq_topic = "afc.msg-verdicts.dlq"
verdicts_signing_public_key = """
-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----
"""

[services.manager_scheduler]
period = "1s"
