[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]

[servers.client.required_access]
resource = "some-resource"
role = "some-role"

[sentry]
dsn = "https://example.com"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "realm"
client_id = "client_id"
client_secret = "secret"
debug_mode = false

[db]
addr = "127.0.0.1:5432"
user = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = true

