openapi: 3.1.0
info:
  title: Bank Support Chat Client Events
  version: v1

servers:
  - url: ws://localhost:8080/ws
    description: Development server

components:
  schemas:
    MessageId:
      required: [ messageId ]
      properties:
        messageId:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    Event:
      required: [ eventType, eventId, requestId ]
      properties:
        eventType:
          $ref: "#/components/schemas/EventType"
        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
      oneOf:
        - $ref: "#/components/schemas/NewMessageEvent"
        - $ref: "#/components/schemas/MessageSentEvent"
        - $ref: "#/components/schemas/MessageBlockedEvent"
      discriminator:
        propertyName: eventType
        mapping:
          NewMessageEvent: "#/components/schemas/NewMessageEvent"
          MessageSentEvent: "#/components/schemas/MessageSentEvent"
          MessageBlockedEvent: "#/components/schemas/MessageBlockedEvent"

    NewMessageEvent:
      allOf:
        - $ref: "#/components/schemas/MessageId"
        - type: object
          required: [ createdAt, isService, body ]
          properties:
            authorId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/evgeniy-krivenko/chat-service/internal/types"
            createdAt:
              type: string
              format: date-time
            body:
              type: string
            isService:
              type: boolean
            authorName:
              type: string

    MessageSentEvent:
      $ref: "#/components/schemas/MessageId"

    MessageBlockedEvent:
      $ref: "#/components/schemas/MessageId"

    EventType:
      type: string
      enum:
        - NewMessageEvent
        - MessageSentEvent
        - MessageBlockedEvent
