openapi: 3.1.0
info:
  title: Bank Support Chat Manager Events
  version: v1

servers:
  - url: ws://localhost:8081/ws
    description: Development server

components:
  schemas:
    MessageId:
      required: [ messageId ]
      properties:
        messageId:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    Event:
      required: [ eventType, eventId, requestId ]
      properties:
        eventType:
          $ref: "#/components/schemas/EventType"
        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
      oneOf:
        - $ref: "#/components/schemas/NewChatEvent"
        - $ref: "#/components/schemas/NewMessageEvent"
      discriminator:
        propertyName: eventType
        mapping:
          NewChatEvent: "#/components/schemas/NewChatEvent"
          NewMessageEvent: "#/components/schemas/NewMessageEvent"

    NewChatEvent:
      required: [ chatId, clientId, canTakeMoreProblems ]
      properties:
        chatId:
          type: string
          format: uuid
          x-go-type: types.ChatID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        clientId:
          type: string
          format: uuid
          x-go-type: types.UserID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        canTakeMoreProblems:
          type: boolean

    NewMessageEvent:
      allOf:
        - $ref: "#/components/schemas/MessageId"
        - type: object
          required: [ createdAt, body, authorId ]
          properties:
            createdAt:
              type: string
              format: date-time
            body:
              type: string
            authorId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    EventType:
      type: string
      enum:
        - NewChatEvent
        - NewMessageEvent
