openapi: 3.0.3
info:
  title: Bank Support Chat Manager API
  version: v1

servers:
  - url: http://localhost:8081/v1
    description: Development server

paths:
  /getFreeHandsBtnAvailability:
    post:
      description: Check availability button
      parameters:
        - $ref: "#/components/parameters/XRequestIDHeader"
      responses:
        '200':
          description: Availability status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFreeHandsBtnAvailabilityResponse"

  /freeHands:
    post:
      description: Signal than manager is free for resolve problems
      parameters:
        - $ref: "#/components/parameters/XRequestIDHeader"
      responses:
        '200':
          description: Result of set manager as free
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FreeHandsResponse"

  /getChats:
    post:
      description: Get the list of chats with open problems.
      parameters:
        - $ref: "#/components/parameters/XRequestIDHeader"
      responses:
        '200':
          description: Chats list.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetChatsResponse"

  /getChatHistory:
    post:
      description: Get manager chat hisroty
      parameters:
        - $ref: "#/components/parameters/XRequestIDHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetChatHistoryRequest"
      responses:
        '200':
          description: Messages list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetChatHistoryResponse"

security:
  - bearerAuth: [ ]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    XRequestIDHeader:
      name: X-Request-ID
      in: header
      required: true
      schema:
        type: string
        format: uuid
        x-go-type: types.RequestID
        x-go-type-import:
          path: "github.com/evgeniy-krivenko/chat-service/internal/types"

  schemas:
    # Common.
    ChatId:
      required: [ chatId ]
      properties:
        chatId:
          type: string
          format: uuid
          x-go-type: types.ChatID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    FreeHandsResponse:
      properties:
        data:
          type: string
          nullable: true
        error:
          $ref: "#/components/schemas/Error"

    GetFreeHandsBtnAvailabilityResponse:
      properties:
        data:
          $ref: "#/components/schemas/GetFreeHandsBtnAvailability"
        error:
          $ref: "#/components/schemas/Error"

    GetFreeHandsBtnAvailability:
      required: [ available, inPool ]
      properties:
        available:
          type: boolean
        inPool:
          type: boolean

    Error:
      required: [ message, code ]
      properties:
        code:
          $ref: "#/components/schemas/ErrorCode"
        message:
          type: string
        details:
          type: string

    ErrorCode:
      type: integer
      description: contains HTTP error codes and specific business logic error codes (the last must be >= 1000).
      enum:
        - 5000
      x-enum-varnames:
        - ErrorCodeManagerOverloaded
      minimum: 400

    GetChatsResponse:
      properties:
        data:
          $ref: "#/components/schemas/ChatList"
        error:
          $ref: "#/components/schemas/Error"

    ChatList:
      required: [ chats ]
      properties:
        chats:
          type: array
          items: { $ref: "#/components/schemas/Chat" }

    Chat:
      allOf:
        - $ref: "#/components/schemas/ChatId"
        - type: object
          required: [ clientId ]
          properties:
            clientId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    GetChatHistoryRequest:
      required: [ chatId ]
      properties:
        chatId:
          type: string
          format: uuid
          x-go-type: types.ChatID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        pageSize:
          type: integer
          minimum: 10
          maximum: 100
        cursor:
          type: string

    GetChatHistoryResponse:
      properties:
        data:
          $ref: "#/components/schemas/MessagesPage"
        error:
          $ref: "#/components/schemas/Error"

    MessageHeader:
      required: [ id, createdAt, authorId ]
      properties:
        id:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        authorId:
          type: string
          format: uuid
          x-go-type: types.UserID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        createdAt:
          type: string
          format: date-time

    MessagesPage:
      required: [ messages, next ]
      properties:
        messages:
          type: array
          items: { $ref: "#/components/schemas/Message" }
        next:
          type: string

    Message:
      allOf:
        - $ref: "#/components/schemas/MessageHeader"
        - required: [ body ]
          properties:
            body:
              type: string
