openapi: 3.1.0
info:
  title: Bank Support Chat Manager Events
  version: v1

servers:
  - url: ws://localhost:8081/ws
    description: Development server

components:
  schemas:
    ChatId:
      required: [ chatId ]
      properties:
        chatId:
          type: string
          format: uuid
          x-go-type: types.ChatID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    MessageId:
      required: [ messageId ]
      properties:
        messageId:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    Event:
      required: [ eventType, eventId, requestId ]
      properties:
        eventType:
          $ref: "#/components/schemas/EventType"
        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/evgeniy-krivenko/chat-service/internal/types"
      oneOf:
        - $ref: "#/components/schemas/NewChatEvent"
        - $ref: "#/components/schemas/NewMessageEvent"
        - $ref: "#/components/schemas/ChatClosedEvent"
      discriminator:
        propertyName: eventType
        mapping:
          NewChatEvent: "#/components/schemas/NewChatEvent"
          NewMessageEvent: "#/components/schemas/NewMessageEvent"
          ChatClosedEvent: "#/components/schemas/ChatClosedEvent"

    NewChatEvent:
      allOf:
        - $ref: "#/components/schemas/ChatId"
        - type: object
          required: [ clientId, canTakeMoreProblems ]
          properties:
            clientId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/evgeniy-krivenko/chat-service/internal/types"
            canTakeMoreProblems:
              type: boolean
            firstName:
              type: string
            lastName:
              type: string

    NewMessageEvent:
      allOf:
        - $ref: "#/components/schemas/MessageId"
        - type: object
          required: [ createdAt, body, authorId, chatId ]
          properties:
            chatId:
              type: string
              format: uuid
              x-go-type: types.ChatID
              x-go-type-import:
                path: "github.com/evgeniy-krivenko/chat-service/internal/types"
            createdAt:
              type: string
              format: date-time
            body:
              type: string
            authorId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/evgeniy-krivenko/chat-service/internal/types"

    ChatClosedEvent:
      allOf:
        - $ref: "#/components/schemas/ChatId"
        - type: object
          required: [ canTakeMoreProblems ]
          properties:
            canTakeMoreProblems:
              type: boolean

    EventType:
      type: string
      enum:
        - NewChatEvent
        - NewMessageEvent
        - ChatClosedEvent
